const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/api/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
   
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./controllers/notes.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app')           // Your project's root file
})